# Generated by Django 3.1.3 on 2021-01-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('genre', models.CharField(blank=True, max_length=30)),
                ('content', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
