# Generated by Django 3.1.3 on 2021-01-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='genre',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
