# Generated by Django 3.1.3 on 2021-01-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20210117_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='genre',
            field=models.CharField(blank=True, choices=[('Science and Technology', 'Science and Technology'), ('Literature', 'Literature'), ('Action', 'Action'), ('Personal Expierence', 'Personal Expierence')], max_length=30, null=True),
        ),
    ]
