# Generated by Django 4.0.2 on 2022-02-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_alter_blog_options_blog_update_time_alter_blog_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
